import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../Components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col antialiased bg-(--color-background) h-screen w-screen overflow-hidden">
        <div className="flex flex-col border-2 m-5 flex-1 overflow-hidden rounded-md">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}